import React, { useState } from 'react';
import {
  Calendar,
  Coins,
  MapPin,
  Users,
  CheckCircle2,
  Clock,
  RotateCw,
  Sliders,
  Bookmark,
  Share2,
  Printer,
  ChevronDown,
  ChevronUp,
  ShieldCheck,
  Bot,
  ExternalLink,
  Plus,
  Compass,
  Sparkles,
  Info,
  Check,
} from 'lucide-react';
import { Plan, TaskItem, ChecklistItem, PlanCategory } from '../types';

interface PlanDashboardProps {
  plan: Plan;
  onRegenerate: () => void;
  onModify: () => void;
  onSave: () => void;
  isSaved: boolean;
  onViewAgentLogs: () => void;
  onUpdateTasks: (tasks: TaskItem[]) => void;
  onUpdateChecklist: (checklist: ChecklistItem[]) => void;
}

export const PlanDashboard: React.FC<PlanDashboardProps> = ({
  plan,
  onRegenerate,
  onModify,
  onSave,
  isSaved,
  onViewAgentLogs,
  onUpdateTasks,
  onUpdateChecklist,
}) => {
  const [activeTab, setActiveTab] = useState<'timeline' | 'budget' | 'tasks' | 'recommendations' | 'agents'>('timeline');
  const [selectedDay, setSelectedDay] = useState<number>(1);
  const [newChecklistText, setNewChecklistText] = useState('');
  const [copiedLink, setCopiedLink] = useState(false);

  // Toggle task status
  const handleToggleTask = (taskId: string) => {
    const updated = plan.tasks.map((t) => {
      if (t.id === taskId) {
        const nextStatus: TaskItem['status'] =
          t.status === 'completed' ? 'todo' : t.status === 'todo' ? 'in_progress' : 'completed';
        return { ...t, status: nextStatus };
      }
      return t;
    });
    onUpdateTasks(updated);
  };

  // Toggle checklist item
  const handleToggleChecklist = (checkId: string) => {
    const updated = plan.checklist.map((c) =>
      c.id === checkId ? { ...c, completed: !c.completed } : c
    );
    onUpdateChecklist(updated);
  };

  // Add custom checklist item
  const handleAddChecklistItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newChecklistText.trim()) return;
    const newItem: ChecklistItem = {
      id: `custom_chk_${Date.now()}`,
      text: newChecklistText.trim(),
      category: 'Custom',
      completed: false,
    };
    onUpdateChecklist([...plan.checklist, newItem]);
    setNewChecklistText('');
  };

  const handleCopyShare = () => {
    navigator.clipboard?.writeText(window.location.href);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  // Budget calculations
  const spendPercent = Math.min(Math.round((plan.estimatedSpend / plan.totalBudget) * 100), 100);
  const remainingPercent = 100 - spendPercent;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      {/* Top Breadcrumb & Actions Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-slate-200 dark:border-slate-800">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-indigo-600 dark:text-indigo-400">
            <span className="capitalize">{plan.inputs.category} Plan</span>
            <span aria-hidden="true">·</span>
            <span>Generated by 6 Autonomous Agents</span>
            <span aria-hidden="true">·</span>
            <span className="text-emerald-600 dark:text-emerald-400 flex items-center gap-1 font-mono">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>Review Certified</span>
            </span>
          </div>
          <h1 className="mt-1 text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">
            {plan.title}
          </h1>
          <p className="mt-1 text-xs sm:text-sm text-slate-500 dark:text-slate-400 max-w-3xl">
            {plan.tagline || plan.summary}
          </p>
        </div>

        {/* Global Action Buttons */}
        <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto justify-end">
          <button
            onClick={onViewAgentLogs}
            className="px-3 py-2 text-xs font-semibold rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors flex items-center gap-1.5 shadow-2xs"
            title="Inspect Agent Activity Logs"
          >
            <Bot className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" />
            <span>Agent Activity</span>
          </button>

          <button
            onClick={onModify}
            className="px-3 py-2 text-xs font-semibold rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors flex items-center gap-1.5 shadow-2xs"
          >
            <Sliders className="w-3.5 h-3.5" />
            <span>Modify Plan</span>
          </button>

          <button
            onClick={onRegenerate}
            className="px-3 py-2 text-xs font-semibold rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors flex items-center gap-1.5 shadow-2xs"
          >
            <RotateCw className="w-3.5 h-3.5" />
            <span>Regenerate</span>
          </button>

          <button
            onClick={onSave}
            className={`px-3 py-2 text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5 shadow-2xs ${
              isSaved
                ? 'bg-emerald-600 text-white'
                : 'bg-indigo-600 hover:bg-indigo-700 text-white'
            }`}
          >
            {isSaved ? <Check className="w-3.5 h-3.5" /> : <Bookmark className="w-3.5 h-3.5" />}
            <span>{isSaved ? 'Saved' : 'Save Plan'}</span>
          </button>

          <button
            onClick={handlePrint}
            aria-label="Print or export plan"
            className="p-2 text-xs font-semibold rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-500 hover:text-slate-900 dark:hover:text-white transition-colors"
          >
            <Printer className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Hero Visual Card / Quick Telemetry Overview */}
      <div className="mt-6 grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Summary & Metadata */}
        <div className="lg:col-span-2 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 flex flex-col justify-between shadow-2xs">
          <div>
            <div className="flex items-center gap-3 text-xs text-slate-500 dark:text-slate-400 font-mono mb-3">
              <span className="flex items-center gap-1">
                <MapPin className="w-3.5 h-3.5 text-indigo-500" />
                <span>{plan.inputs.location}</span>
              </span>
              <span aria-hidden="true">·</span>
              <span className="flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-indigo-500" />
                <span>{plan.inputs.durationDays} Days</span>
              </span>
              <span aria-hidden="true">·</span>
              <span className="flex items-center gap-1">
                <Users className="w-3.5 h-3.5 text-indigo-500" />
                <span>{plan.inputs.numPeople} Person(s)</span>
              </span>
            </div>

            <h2 className="text-base font-bold text-slate-900 dark:text-white mb-2">
              AI-Generated Strategy & Summary
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
              {plan.summary}
            </p>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500 dark:text-slate-400">
            <div className="flex items-center gap-2">
              <span className="font-semibold text-slate-900 dark:text-white">Priorities:</span>
              <span className="truncate max-w-xs">{plan.inputs.priorities}</span>
            </div>
            <div className="flex items-center gap-1.5 text-indigo-600 dark:text-indigo-400 font-semibold cursor-pointer" onClick={onViewAgentLogs}>
              <span>Inspect 6 Agent Traces</span>
              <ExternalLink className="w-3 h-3" />
            </div>
          </div>
        </div>

        {/* Right: Financial Health & Budget Quick Card */}
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 flex flex-col justify-between shadow-2xs">
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 dark:text-slate-500">
                Financial Health
              </span>
              <span className="text-xs font-mono font-semibold text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/50 px-2 py-0.5 rounded">
                Under Budget Cap
              </span>
            </div>

            <div className="flex items-baseline gap-2 mt-2">
              <span className="text-2xl sm:text-3xl font-extrabold font-mono text-slate-900 dark:text-white tabular-nums">
                {plan.currency}{plan.estimatedSpend.toLocaleString()}
              </span>
              <span className="text-xs text-slate-500 dark:text-slate-400 font-mono">
                / {plan.currency}{plan.totalBudget.toLocaleString()} max
              </span>
            </div>

            {/* Visual Budget Bar */}
            <div className="mt-4">
              <div className="h-2.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden flex">
                <div
                  style={{ width: `${spendPercent}%` }}
                  className="bg-indigo-600 dark:bg-indigo-500 h-full rounded-l-full transition-all duration-500"
                />
                <div
                  style={{ width: `${remainingPercent}%` }}
                  className="bg-emerald-500 dark:bg-emerald-400 h-full rounded-r-full transition-all duration-500"
                />
              </div>

              <div className="mt-2 flex items-center justify-between text-xs font-mono">
                <span className="text-slate-600 dark:text-slate-400">
                  Estimated: {plan.currency}{plan.estimatedSpend.toLocaleString()} ({spendPercent}%)
                </span>
                <span className="text-emerald-600 dark:text-emerald-400 font-semibold">
                  Buffer: {plan.currency}{plan.remainingBudget.toLocaleString()} ({remainingPercent}%)
                </span>
              </div>
            </div>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800 text-[11px] text-slate-500 dark:text-slate-400 flex items-center justify-between">
            <span>Contingency Cushion:</span>
            <span className="font-semibold text-slate-900 dark:text-white font-mono">
              +{plan.currency}{plan.remainingBudget.toLocaleString()} Liquid Buffer
            </span>
          </div>
        </div>
      </div>

      {/* Main Tab Navigation */}
      <div className="mt-8 border-b border-slate-200 dark:border-slate-800">
        <nav className="flex space-x-2 sm:space-x-6 overflow-x-auto pb-px">
          {[
            { id: 'timeline', label: `Timeline (${plan.days.length} Days)` },
            { id: 'budget', label: 'Budget Breakdown' },
            { id: 'tasks', label: `Actionable Tasks (${plan.tasks.filter((t) => t.status === 'completed').length}/${plan.tasks.length})` },
            { id: 'recommendations', label: 'Recommendations & Tips' },
            { id: 'agents', label: 'Agent Verification Audit' },
          ].map((tab) => {
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`py-3 px-2 sm:px-3 text-xs sm:text-sm font-semibold border-b-2 whitespace-nowrap transition-colors ${
                  isActive
                    ? 'border-indigo-600 text-indigo-600 dark:border-indigo-400 dark:text-indigo-400'
                    : 'border-transparent text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
                }`}
              >
                {tab.label}
              </button>
            );
          })}
        </nav>
      </div>

      {/* Tab 1: Timeline & Itinerary */}
      {activeTab === 'timeline' && (
        <div className="mt-6 space-y-6">
          {/* Day selection tabs */}
          {plan.days.length > 1 && (
            <div className="flex items-center gap-2 overflow-x-auto pb-2">
              {plan.days.map((day) => {
                const isSelected = selectedDay === day.dayNumber;
                return (
                  <button
                    key={day.dayNumber}
                    onClick={() => setSelectedDay(day.dayNumber)}
                    className={`px-4 py-2 text-xs font-semibold rounded-xl border transition-all whitespace-nowrap ${
                      isSelected
                        ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 shadow-2xs'
                        : 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'
                    }`}
                  >
                    Day {day.dayNumber}: {day.title.split(':')[1] || day.title}
                  </button>
                );
              })}
            </div>
          )}

          {/* Active Day Card */}
          {plan.days
            .filter((d) => (plan.days.length > 1 ? d.dayNumber === selectedDay : true))
            .map((day) => (
              <div
                key={day.dayNumber}
                className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-2xs"
              >
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800 gap-2">
                  <div>
                    <span className="text-xs font-mono font-bold text-indigo-600 dark:text-indigo-400">
                      Day {day.dayNumber} Schedule
                    </span>
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                      {day.title}
                    </h3>
                  </div>
                  <span className="text-xs text-slate-500 dark:text-slate-400 italic">
                    Theme: {day.theme}
                  </span>
                </div>

                {/* Activities chronological list */}
                <div className="mt-6 space-y-4">
                  {day.activities.map((act, index) => (
                    <div
                      key={act.id || index}
                      className="p-4 rounded-xl border border-slate-200/80 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 bg-slate-50/40 dark:bg-slate-950/30 transition-all flex flex-col md:flex-row items-start md:items-center justify-between gap-3"
                    >
                      <div className="space-y-1">
                        <div className="flex items-center gap-2 text-xs font-mono text-slate-500 dark:text-slate-400">
                          <Clock className="w-3.5 h-3.5 text-indigo-500" />
                          <span>{act.time}</span>
                          {act.location && (
                            <>
                              <span aria-hidden="true">·</span>
                              <span className="text-slate-700 dark:text-slate-300 flex items-center gap-1 font-sans">
                                <MapPin className="w-3 h-3 text-slate-400" />
                                <span>{act.location}</span>
                              </span>
                            </>
                          )}
                        </div>

                        <h4 className="text-sm font-bold text-slate-900 dark:text-white">
                          {act.title}
                        </h4>
                        <p className="text-xs text-slate-600 dark:text-slate-300 max-w-2xl leading-relaxed">
                          {act.description}
                        </p>
                      </div>

                      <div className="flex md:flex-col items-center md:items-end justify-between w-full md:w-auto pt-2 md:pt-0 border-t md:border-t-0 border-slate-200/60 dark:border-slate-800 gap-1 shrink-0">
                        {act.estimatedCost !== undefined && (
                          <span className="text-xs font-mono font-bold text-slate-900 dark:text-white tabular-nums">
                            ~{plan.currency}{act.estimatedCost.toLocaleString()}
                          </span>
                        )}
                        {act.tag && (
                          <span className="text-[11px] font-medium text-slate-500 dark:text-slate-400">
                            {act.tag}
                          </span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
        </div>
      )}

      {/* Tab 2: Budget Breakdown */}
      {activeTab === 'budget' && (
        <div className="mt-6 space-y-6">
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-2xs">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
              <div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Categorical Cost Breakdown
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Audited by Budget Agent with variance controls
                </p>
              </div>
              <div className="text-right">
                <span className="text-xs text-slate-400 block font-mono">Total Planned</span>
                <span className="text-base font-bold font-mono text-slate-900 dark:text-white tabular-nums">
                  {plan.currency}{plan.estimatedSpend.toLocaleString()}
                </span>
              </div>
            </div>

            {/* Table */}
            <div className="mt-4 overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-500 font-semibold uppercase tracking-wider">
                    <th className="py-2.5 px-3">Category</th>
                    <th className="py-2.5 px-3">Notes & Scope</th>
                    <th className="py-2.5 px-3 text-right">Allocated</th>
                    <th className="py-2.5 px-3 text-right">Estimated</th>
                    <th className="py-2.5 px-3 text-right">Variance</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/80 font-mono">
                  {plan.budgetBreakdown.map((item) => {
                    const variance = item.allocated - item.estimated;
                    return (
                      <tr key={item.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/40 transition-colors">
                        <td className="py-3 px-3 font-sans font-bold text-slate-900 dark:text-white">
                          {item.category}
                        </td>
                        <td className="py-3 px-3 font-sans text-slate-600 dark:text-slate-300">
                          {item.notes}
                        </td>
                        <td className="py-3 px-3 text-right text-slate-500 tabular-nums">
                          {plan.currency}{item.allocated.toLocaleString()}
                        </td>
                        <td className="py-3 px-3 text-right font-bold text-slate-900 dark:text-white tabular-nums">
                          {plan.currency}{item.estimated.toLocaleString()}
                        </td>
                        <td className={`py-3 px-3 text-right font-semibold tabular-nums ${
                          variance >= 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-500'
                        }`}>
                          {variance >= 0 ? `+${plan.currency}${variance.toLocaleString()}` : `-${plan.currency}${Math.abs(variance).toLocaleString()}`}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr className="border-t-2 border-slate-200 dark:border-slate-700 font-mono font-bold text-slate-900 dark:text-white">
                    <td colSpan={3} className="py-3 px-3 font-sans">
                      Remaining Unallocated Contingency Buffer:
                    </td>
                    <td colSpan={2} className="py-3 px-3 text-right text-emerald-600 dark:text-emerald-400 tabular-nums">
                      {plan.currency}{plan.remainingBudget.toLocaleString()}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Tab 3: Actionable Tasks & Checklist */}
      {activeTab === 'tasks' && (
        <div className="mt-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left: Actionable Tasks */}
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-2xs">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800">
              <div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Actionable Milestones
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Assigned by Planner & Schedule Agents
                </p>
              </div>
              <span className="text-xs font-mono text-slate-400">
                Tap to toggle status
              </span>
            </div>

            <div className="mt-4 space-y-3">
              {plan.tasks.map((task) => {
                const isDone = task.status === 'completed';
                const isInProg = task.status === 'in_progress';

                return (
                  <div
                    key={task.id}
                    onClick={() => handleToggleTask(task.id)}
                    className={`p-3.5 rounded-xl border transition-all cursor-pointer flex items-center justify-between gap-3 ${
                      isDone
                        ? 'border-emerald-200 dark:border-emerald-900/60 bg-emerald-50/30 dark:bg-emerald-950/20'
                        : isInProg
                        ? 'border-amber-200 dark:border-amber-900/60 bg-amber-50/30 dark:bg-amber-950/20'
                        : 'border-slate-200 dark:border-slate-800 hover:border-slate-300'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className={`w-5 h-5 rounded-md flex items-center justify-center border transition-colors ${
                        isDone
                          ? 'bg-emerald-600 border-emerald-600 text-white'
                          : isInProg
                          ? 'border-amber-500 text-amber-500'
                          : 'border-slate-300 dark:border-slate-600'
                      }`}>
                        {isDone && <Check className="w-3.5 h-3.5" />}
                        {isInProg && <div className="w-2 h-2 rounded-full bg-amber-500" />}
                      </div>

                      <div>
                        <span className={`text-xs sm:text-sm font-semibold block ${
                          isDone ? 'line-through text-slate-400 dark:text-slate-500' : 'text-slate-900 dark:text-white'
                        }`}>
                          {task.title}
                        </span>
                        <div className="flex items-center gap-2 text-[11px] text-slate-400 mt-0.5">
                          <span>{task.category}</span>
                          <span aria-hidden="true">·</span>
                          <span className="capitalize">{task.assignedAgent} Agent</span>
                        </div>
                      </div>
                    </div>

                    <span className={`text-[11px] font-mono font-semibold px-2 py-0.5 rounded capitalize ${
                      isDone
                        ? 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300'
                        : isInProg
                        ? 'bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300'
                        : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                    }`}>
                      {task.status.replace('_', ' ')}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right: Preparation / Packing Checklist */}
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-2xs">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 dark:border-slate-800">
              <div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Preparation & Packing Checklist
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  {plan.checklist.filter((c) => c.completed).length} of {plan.checklist.length} items packed
                </p>
              </div>
            </div>

            {/* Checklist items */}
            <div className="mt-4 space-y-2 max-h-[360px] overflow-y-auto pr-1">
              {plan.checklist.map((item) => (
                <label
                  key={item.id}
                  className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/40 cursor-pointer transition-colors"
                >
                  <input
                    type="checkbox"
                    checked={item.completed}
                    onChange={() => handleToggleChecklist(item.id)}
                    className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-slate-300 dark:border-slate-700 bg-transparent"
                  />
                  <span className={`text-xs sm:text-sm ${
                    item.completed ? 'line-through text-slate-400 dark:text-slate-500' : 'text-slate-700 dark:text-slate-200'
                  }`}>
                    {item.text}
                  </span>
                </label>
              ))}
            </div>

            {/* Add custom checklist item */}
            <form onSubmit={handleAddChecklistItem} className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800 flex gap-2">
              <input
                type="text"
                value={newChecklistText}
                onChange={(e) => setNewChecklistText(e.target.value)}
                placeholder="Add custom item to checklist..."
                className="flex-1 px-3 py-1.5 text-xs rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 focus:outline-none"
              />
              <button
                type="submit"
                className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-semibold flex items-center gap-1 transition-colors"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add</span>
              </button>
            </form>
          </div>
        </div>
      )}

      {/* Tab 4: Recommendations & Tips */}
      {activeTab === 'recommendations' && (
        <div className="mt-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {plan.recommendations.map((rec) => (
              <div
                key={rec.id}
                className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 flex flex-col justify-between shadow-2xs hover:border-slate-300 dark:hover:border-slate-700 transition-all"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
                      {rec.category} Recommendation
                    </span>
                    {rec.rating && (
                      <span className="text-xs font-mono font-bold text-amber-500 flex items-center gap-1">
                        ★ {rec.rating}
                      </span>
                    )}
                  </div>

                  <h3 className="text-base font-bold text-slate-900 dark:text-white">
                    {rec.title}
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                    {rec.subtitle}
                  </p>
                  <p className="mt-3 text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                    {rec.description}
                  </p>
                </div>

                <div className="mt-5 pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                  <div className="flex flex-wrap gap-1.5">
                    {rec.tags.map((tag, i) => (
                      <span key={i} className="text-[11px] font-medium text-slate-500 dark:text-slate-400">
                        #{tag}
                      </span>
                    ))}
                  </div>
                  {rec.priceHint && (
                    <span className="font-mono text-slate-700 dark:text-slate-300 font-semibold">
                      {rec.priceHint}
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Important Tips Callout */}
          <div className="bg-amber-50/50 dark:bg-amber-950/20 rounded-2xl border border-amber-200/80 dark:border-amber-900/40 p-6">
            <h3 className="text-sm font-bold text-amber-900 dark:text-amber-200 flex items-center gap-2 mb-3">
              <Info className="w-4 h-4 text-amber-600 dark:text-amber-400" />
              <span>Important Tips & Operational Guidelines</span>
            </h3>
            <ul className="space-y-2 text-xs sm:text-sm text-amber-900/80 dark:text-amber-300/80">
              {plan.importantTips.map((tip, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-2 shrink-0" />
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Tab 5: Agent Verification Audit */}
      {activeTab === 'agents' && (
        <div className="mt-6 space-y-6">
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-2xs">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
              <div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Review Agent Quality & Conflict Audit
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Continuous verification pass executed before presenting the plan
                </p>
              </div>
              <span className="text-xs font-mono font-semibold px-2.5 py-1 rounded bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300">
                100% Certified
              </span>
            </div>

            <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
                  Conflict Verification
                </h4>
                <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-950/50 border border-slate-200 dark:border-slate-800 space-y-1">
                  <span className="text-lg font-bold font-mono text-emerald-600 dark:text-emerald-400">
                    0 Conflicts Detected
                  </span>
                  <p className="text-xs text-slate-500">
                    Transit schedules and opening hours cross-validated with zero overlaps.
                  </p>
                </div>
              </div>

              <div className="md:col-span-2">
                <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
                  Autonomous Optimizations Applied
                </h4>
                <ul className="space-y-1.5 text-xs text-slate-700 dark:text-slate-300">
                  {plan.reviewAudit.optimizationsMade.map((opt, i) => (
                    <li key={i} className="flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                      <span>{opt}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800">
              <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-3">
                Full Agent Execution Trace
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                {plan.agentLogs.map((log) => (
                  <div
                    key={log.id}
                    className="p-3 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/40 text-xs"
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-bold text-slate-900 dark:text-white">
                        {log.agentName}
                      </span>
                      <span className="font-mono text-slate-400 text-[10px]">
                        {log.timestamp}
                      </span>
                    </div>
                    <p className="text-slate-600 dark:text-slate-300 leading-snug">
                      {log.statusMessage}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
